AWSTemplateFormatVersion: '2010-09-09'
Description: "Template to launch an EC2 instance for stagging"

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: devops_cisly
      InstanceType: t2.micro
      SecurityGroupIds: 
          - 'sg-069bf594e4a38e030'
      ImageId: ami-003932de22c285676
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 8
            VolumeType: gp2
      Tags:
        - Key: Name
          Value: stagging_server
      UserData:
        Fn::Base64: |
          #!/bin/bash
          apt-get update -y
          sudo add-apt-repository ppa:deadsnakes/ppa -y
          sudo apt install -y python3.8 python3.8-venv
          sudo apt install -y ruby wget
          wget https://aws-codedeploy-us-west-2.s3.us-west-2.amazonaws.com/latest/install
          chmod +x ./install
          sudo ./install auto
          sudo service codedeploy-agent start
          sudo reboot
    DeletionPolicy: Delete

