AWSTemplateFormatVersion: '2010-09-09'
Description: "Membuat bucket S3 baru"

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: my-bucket-warrior-123456 # Ganti dengan nama bucket yang unik
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: MyS3Bucket
    DeletionPolicy: Delete
